services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  blob:
    image: minio/minio:latest
    container_name: blob
    command: server /data --console-address ":9001"
    env_file:
      - .env.development
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - blob_data:/data

volumes:
  postgres_data:
  blob_data: